### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by j6s** [Weebly/phpstan-laravel#29]
I am a big fan of this project - however there has been very little momentum in it in the last couple of years.

I had to drop it in favour of my own fork about 1.5 years ago as this project stopped being updated for newer laravel and phpstan versions. As it stands `phpstan-laravel` only supports outdated versions of both.

This is a shame, because using PHPStan in laravel projects has helped my codebases a lot.
At this point I am proposing that I may take over some of the maintainance of the package to let it gain some momentum again.

I know this is a lot to ask for. If you are not comfortable with this I will go ahead and fork the project - but that's a situation I want to avoid.

**Comment by szainmehdi** [comment]
This package is no longer maintained. We recommend using https://github.com/nunomaduro/larastan.

**Comment by mfn** [comment]
@szainmehdi I suggest to use the Github feature archive to send a clear message about this repository state => see https://help.github.com/en/articles/archiving-a-github-repository
